### ISSUE TITLE
Simplify the AST, remove the ASTConverter from the code generation pipeline, and use the AST directly

### ISSUE THREAD

**Issue by dgavedissian** [TheComet/OpenDarkBASIC#78]
When working on code generation, I added the IR, which is essentially a different version of the AST with tighter semantics and type safety after running type checks and command lookups and so on. This also made writing the backend significantly faster, as I wasn't constrained by the design of the AST.

Now we have an almost complete AST, and a partially written IR, I wonder whether there's a path to unifying the data strctures? For example, does the IR contain some ideas that the AST tree could adopt? Could the AST nodes start of as "Unchecked" nodes that get replaced with "Checked" nodes with tighter semantics/type safety, essentially turning the IR phase of the compiler into an "astpost" pass?

Something for me to do eventually.

**Comment by dgavedissian** [comment]
Here's I've written down some ideas on what to change in the AST.

Renames:
- [ ] Rename `astpost` to `passes`.
- [x] Rename "symbol" to "identifier".
- [ ] Rename `Stmnt` to `Stmt`, so it can be 4 characters like Node, Expr.
- [ ] Rename `ArrayDecl` to `AllocateArray`. a `DIM` command is an array allocation, not a declaration, as you can call `DIM` multiple times.
- [ ] Rename `Reference<T>` to `SharedPtr<T>`

Restructuring:
- [x] Move `ir::Type` to `ast` (#81)
- [x] Remove the type specific variants of `ast::VarDecl` and `ast::ArrayDecl`, like `ast::IntegerVarDecl`, and add `ast::Type` as a member of `ast::VarDecl` and `ast::ArrayDecl`.  I think it's easier for later code when we composition over inheritance for storing the type information  (#81)
- [x] Merge `ScopedAnnotatedSymbol`, `AnnotatedSymbol` and `Symbol` into a single class `Identifier` (with an optional annotation and optional scope). Again, I think it's easier for later code to handle composition over inheritance for these two attributes.
- [ ] Replace `MaybeNull<ArgList>` with just an `ArgList` that's empty. Honestly, we could probably replace `ArgList` with just a `std::vector`
- [ ] Revisit what nodes use intrusive reference counting and what ndoes don't. For example, we could just use unique_ptr throughout where a child node is owned by the parent node, and only use `Reference` for things which are actually shared i.e. Variables, Labels, etc.
- [x] Revisit the `Visitor` pattern - could we generate more of the repetitive code? Maybe there's a cleaner way to express it.  (#82)
  * Replace `Node::accept()` with `Node::children()` that returns a list of all children in the tree (could be in the form of two iterators?), then we can write a function that traverses through the tree iteratively using `Node::children()`
  * Maybe there's a way to remove the need for `parent()` and `swapChild()`. Maybe the visit functions receive a pointer to the parent node as well as the current node?
